version: '3.9'

services:
  postgres:
    image: postgres:15.3-alpine3.18
    ports:
      - '5432:5432'
    volumes:
      - TekChatPostgresData:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - TekChatNetwork
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - TekChatRedisData:/data
    networks:
      - TekChatNetwork
  api:
    image: tekchat-main:${IMAGE_TAG:-develop}
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - TekChatNetwork

volumes:
  TekChatPostgresData:
  TekChatRedisData:

networks:
  TekChatNetwork:
    name: TekChatNetwork
    driver: bridge
    attachable: true
