export const MAIL_QUEUE = 'MAIL_QUEUE';
export const MESSAGE_QUEUE = 'MESSAGE_QUEUE';
export const MESSAGE_JOB = {
  UPLOAD_ATTACHMENT: 'UPLOAD_ATTACHMENT',
  UPLOAD_CONVERSATION_AVATAR: 'UPLOAD_CONVERSATION_AVATAR',
};
